   name: Deploy SpringBoot and Angular app to EC2
   on:
     push:
       branches:
         - main
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'adopt'
         - name:  Build and package SpringBoot app with Maven
           run: |
             cd stringboot-app
             mvn clean install -DskipTests
         - name: Build and package Angular app
           run: |
             cd angular-app
             npm install
             npm run build
         - name: Deploy to EC2
           uses: appleboy/ssh-action@master
           with:
             host: 13.113.194.194
             username: ec2-user
             key: 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdz
c2gtcnNhAAAAAwEAAQAAAQEAwfh6FDrUV/MU45gGnsuthjAn/AhkTkcJrnmhO750
8TPlZUUx0TCWgko5MhZz/TzVVJqzLsCNmeQLYW7TRPa7Sql+tIcIq0t74jGp7RQp
nyZ37mcML+ysmp6DN6Csx2v6p4URQwqBE5xFQDX3J9iBJO1xbesD1Bh4x5kLRB+Q
3+6QjI1mOSyc+qrq1hok22tEFS6s7tWW+KJAFS/Wc5251b+6j9YX1WBtAoWIWnKJ
gnyoxQ9QbuJzA6lF1cAAq70vROkqAW3uzURt5nofDUE8HYHnDEz/ShZpw0dnek6g
yYM+iIYn++PX7bBZWhu5No8jHYQfGrQEHCouWxPBiRS4bQAAA9Co9E8EqPRPBAAA
AAdzc2gtcnNhAAABAQDB+HoUOtRX8xTjmAaey62GMCf8CGRORwmueaE7vnTxM+Vl
RTHRMJaCSjkyFnP9PNVUmrMuwI2Z5AthbtNE9rtKqX60hwirS3viMantFCmfJnfu
Zwwv7KyanoM3oKzHa/qnhRFDCoETnEVANfcn2IEk7XFt6wPUGHjHmQtEH5Df7pCM
jWY5LJz6qurWGiTba0QVLqzu1Zb4okAVL9ZznbnVv7qP1hfVYG0ChYhacomCfKjF
D1Bu4nMDqUXVwACrvS9E6SoBbe7NRG3meh8NQTwdgecMTP9KFmnDR2d6TqDJgz6I
hif749ftsFlaG7k2jyMdhB8atAQcKi5bE8GJFLhtAAAAAwEAAQAAAQEAtzlRh95y
Somxh7NJPaLDzOecPXRn25E60fbOmLK1oEoXPGv6PNIaugQGtwuCkQlvsjVXYKg+
mclR/r1DD/fIvyQQLdMIG1Z4NRgYnXvYPR+HVkk8t+Bmwr9Mz7UUwGN9J9SIk71O
ZAnPWHIhfyACDbHE3cGLokNjg5dLjxQKM5trU1FSZ68fnTXQSlUuT4aaxmh34F2x
40dvZxmyFbyPROKHA1Xpwnka+Y3QIWj3kTXKN4u51cMI8JUm6UxzKhTl5B6X/wV3
lwPNexqloszOlYO7tpNL85UA5kSPMcsxAASNfmJJgR/lFQksuC23tv0bfXEcYYRq
0gVmgizDq88cuQAAAIEA1B8e9Z+k/4vPE8wW6Pqwej4A5g/mZPXUGElS/9z9O43Y
jJzJrqX4T3q25pKhb1gaXcZnCW5v/AimhK3K7Oz92foAn2u+bj3OQPe8ulM7ruLJ
PAfnVV71nv3uNrL/yFKgX1WkpC+g5gimU6t5fJesOJOW9ybbzEOP3mhnaP9lzc8A
AACBAP8a0oNDcKA2fxEFsX/oyD49flYSS/huTrb4eT3TwGVDvZyDgQC9GkIvy2Jw
p7u3uBYLok6ZEgQ3PzlHx0DKRBQndXQxxQHSMrx1lKpk94q+QfdMIxtdbA2PWThr
4osPr7UcoT4ag2yFgrxKBP50W8x3EOLIANLOKwVfgkquFmLnAAAAgQDCprvQY2NQ
F1wBHYroIqCZKaD6yAlZddFpTzm/HCTu3niJSy1Hfif1AOxo7MX6YuzBDPvkhrw/
599NsSYx0HwoaxHRoHY1NLe9cBoP24fbdbg8U66l27Tvr/Er9jAP0u3wR3JRCsPl
xEUxq/aKcFWvL0sGUllsDIiyssG/qt8ziwAAABRpbXBvcnRlZC1vcGVuc3NoLWtl
eQECAwQF'
             port: 22
             script: |
               cd /home/ec2-user/app
               # stop existing application
               ./stop.sh
               # remove existing app
               rm -rf ./dist
               rm -rf ./build
               # remove existing jar
               rm -f ./build/libs/*.jar
               # copy new app
               mkdir -p ./dist
               mkdir -p ./build/libs
               scp -r ./angular-app/dist ./dist
               scp ./build/libs/*.jar ./build/libs/
               # start new application
               ./start.sh
