   name: Deploy SpringBoot and Angular app to EC2
   on:
     push:
       branches:
         - main
   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: Set up JDK 17
           uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'adopt'
         - name:  Build and package SpringBoot app with Maven
           run: |
             cd stringboot-app
             mvn clean install -DskipTests
         - name: Build and package Angular app
           run: |
             cd angular-app
             npm install
             npm run build angular-app --prod
         - name: Copy files to EC2
           uses: appleboy/scp-action@master
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_PRIVATE_KEY }}
             port: 22
             source: "./angular-app/dist/angular-app/*, ./stringboot-app/target/*.jar"
             target: "/usr/local/bin/myapp/temp-copy" # EC2上のデプロイ先ディレクトリ
         - name: Deploy to EC2
           uses: appleboy/ssh-action@master
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_PRIVATE_KEY }}
             port: 22
             script: |
               echo "サーバ配置開始！！"
               cd /usr/local/bin/myapp
               # stop existing application
               # pkill -f 'java -jar app.jar' || true
               sudo systemctl stop myapp
               sleep 2
               # 新しいjarを配置
               cp ./temp-copy/stringboot-app/target/*.jar ./app.jar
               # Angularのファイルを配置
               rm -rf ./static
               mkdir ./static
               cp -r ./temp-copy/angular-app/dist/angular-app/* ./static/
               rm -rf ./temp-copy/stringboot-app
               rm -rf ./temp-copy/angular-app
               echo "サーバ配置完了！！"
               sudo systemctl start myapp
